##
# This file is part of RGPD project.
#
# (c) Sébastien CHOMY <sebastien.chomy@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##
twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    strict_variables: '%kernel.debug%'
